# Generated by Django 3.1.7 on 2021-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
