# Generated by Django 3.1.7 on 2021-03-28 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210328_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='rating',
        ),
        migrations.AddField(
            model_name='courier',
            name='orders',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
