# Generated by Django 3.1.7 on 2021-03-28 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courier_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='cur_orders',
            field=models.CharField(default=datetime.datetime(2021, 3, 28, 17, 30, 25, 413508, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
